defaults:
  - _self_
  - features: default
  - model: logistic_regression
  - preprocessing: one_hot_transformer
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

save_output: true

input_data_path: data/raw/heart_cleveland_upload.csv
model_path: artifacts/train/${model.model_type}/model.pkl
transformer_path: artifacts/train/${model.model_type}/transformer.pkl
output_inference_data_path: artifacts/inference/${model.model_type}/inference.csv

hydra:
    run:
      dir: artifacts/inference/${model.model_type}/
    sweep:
      dir: artifacts/inference/${model.model_type}/
      subdir: ${hydra.job.override_dirname}
    job_logging:
      handlers:
        file:
          mode: 'w'
